# Generated by Django 5.0.6 on 2024-05-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materia', '0001_initial'),
        ('profesor', '0001_initial'),
        ('publicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='profesores',
            field=models.ManyToManyField(through='publicacion.Publicacion', to='profesor.profesor'),
        ),
    ]
