# Generated by Django 5.0.6 on 2024-05-25 16:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profesor', '0002_initial'),
        ('publicacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='usuarios',
            field=models.ManyToManyField(through='publicacion.Publicacion', to=settings.AUTH_USER_MODEL),
        ),
    ]
