# Generated by Django 5.2 on 2025-11-06 03:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='tipoEnsenanza',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
