# Generated by Django 5.2 on 2025-11-06 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0004_profesor_tipoensenanza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='tipoEnsenanza',
        ),
    ]
