# Generated by Django 5.2 on 2025-11-06 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0005_remove_profesor_tipoensenanza'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='metodoEnsenanza',
            field=models.CharField(choices=[('visual', 'Visual'), ('auditivo', 'Auditivo'), ('kinestesico', 'Kinestésico'), ('lector', 'Lector/Escritor')], default='visual', max_length=20),
        ),
    ]
