# Generated by Django 5.2 on 2025-11-06 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0006_profesor_metodoensenanza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='metodoEnsenanza',
        ),
        migrations.AddField(
            model_name='profesor',
            name='metodo_ensenanza',
            field=models.CharField(choices=[('visual', 'Visual'), ('auditivo', 'Auditivo'), ('kinestesico', 'Kinestésico')], default='visual', max_length=20),
        ),
    ]
