# Generated by Django 5.2 on 2025-11-06 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='metodo_aprendizaje',
            field=models.CharField(blank=True, choices=[('visual', 'Visual'), ('auditivo', 'Auditivo'), ('kinestesico', 'Kinestésico')], max_length=20, null=True),
        ),
    ]
