# Generated by Django 5.2 on 2025-11-08 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='dificultad',
            new_name='facilidad',
        ),
    ]
